// Create a user
POST http://localhost:5000/users
Content-Type: application/json

{
    "name": "Higa",
    "email": "higa@gmail.com",
    "password": "123456",
    "confPassword": "123456",
    "role": "admin"
}

###
// Get all Users
GET http://localhost:5000/users

###
//Get User by Id
GET http://localhost:5000/users/1

###
//Update User
PATCH  http://localhost:5000/users/1
Content-Type: application/json

{
    "name": "Bryant Sulthan",
    "email": "bryant@gmail.com",
    "password": "123456",
    "confPassword": "123456",
    "role": "admin"
}

###
//Delete User
DELETE  http://localhost:5000/users/3

###
//Login
POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "lorem@gmail.com",
    "password": "123456"
}

###
//Me
GET http://localhost:5000/me

###
//Logout
DELETE http://localhost:5000/logout

###
// Get all products
GET http://localhost:5000/products

###
// Create Product
POST http://localhost:5000/products
Content-Type: application/json

{
    "name": "Bakso Bakar",
    "price": 25000
}

###
//Get Product by ID
GET http://localhost:5000/products/1

###
//Update Product
PATCH  http://localhost:5000/products/1
Content-Type: application/json

{
    "name": "Bakso",
    "price": 15000
}

###
//Delete Product
DELETE  http://localhost:5000/products/10
